/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

/**
 *
 * @author ACER
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInput = new javax.swing.JMenu();
        menuItemPelanggan = new javax.swing.JMenuItem();
        menuItemDataBuku = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuItemPenjualanBuku = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuItemLaporanPenjualan = new javax.swing.JMenuItem();
        menuItemLaporanBuku = new javax.swing.JMenuItem();
        menuItemLaporanPelanggan = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItemTentangAplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        menuInput.setText("Input");

        menuItemPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemPelanggan.setText("Data Pelanggan");
        menuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPelangganActionPerformed(evt);
            }
        });
        menuInput.add(menuItemPelanggan);

        menuItemDataBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemDataBuku.setText("Data Buku");
        menuItemDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDataBukuActionPerformed(evt);
            }
        });
        menuInput.add(menuItemDataBuku);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuInput.add(menuItemExit);

        jMenuBar1.add(menuInput);

        menuTransaksi.setText("Transaksi");

        menuItemPenjualanBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemPenjualanBuku.setText("Penjualan Buku");
        menuItemPenjualanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPenjualanBukuActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuItemPenjualanBuku);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setText("Laporan");

        menuItemLaporanPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemLaporanPenjualan.setText("Laporan Penjualan");
        menuItemLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanPenjualanActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporanPenjualan);

        menuItemLaporanBuku.setText("Laporan Data Buku");
        menuItemLaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanBukuActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporanBuku);

        menuItemLaporanPelanggan.setText("Laporan Data Pelanggan");
        menuItemLaporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanPelangganActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporanPelanggan);

        jMenuBar1.add(menuLaporan);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });

        menuItemTentangAplikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemTentangAplikasi.setText("Tentang Aplikasi");
        menuAbout.add(menuItemTentangAplikasi);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPelangganActionPerformed
        // TODO add your handling code here:
        FrmPelanggan pelanggan=new FrmPelanggan();
        jDesktopPaneBackground2.add(pelanggan);
        pelanggan.setVisible(true);
    }//GEN-LAST:event_menuItemPelangganActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLaporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanPelangganActionPerformed
        // TODO add your handling code here
        LaporanDataPelanggan laporanDataPelanggan=new LaporanDataPelanggan();
        JDesktopPaneBackground2.add(laporanDataPelanggan);
    }//GEN-LAST:event_menuItemLaporanPelangganActionPerformed

    private void menuItemLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanBukuActionPerformed
        // TODO add your handling code here:
        laporanDataBuku laporanDataBuku=new LaporanDataBuku();
        JDesktopPaneBackground2.add(laporanDataBuku);
        laporanDataBuku.setVisible(true);
    }//GEN-LAST:event_menuItemLaporanBukuActionPerformed

    private void menuItemDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDataBukuActionPerformed
        // TODO add your handling code here:
        FrmBuku buku=new FrmBuku();
        jDesktoppaneBackground2.add(buku);
        buku.setVisible(true);
    }//GEN-LAST:event_menuItemDataBukuActionPerformed

    private void menuItemPenjualanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPenjualanBukuActionPerformed
        // TODO add your handling code here:
        FrmPenjualanBuku jualBuku=new FrmPenjualanBuku();
        JDesktopPaneBackground.add(jualBuku);
        jualBuku.setVisible(true);
    }//GEN-LAST:event_menuItemPenjualanBukuActionPerformed

    private void menuItemLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualanBuku laporanPenjualanBuku=new LaporanPenjualanBuku();
        JDesktopPaneBackground2.add(laporanPenjualanBuku);
        laporanPenjualanBuku.setVisible(true);
    }//GEN-LAST:event_menuItemLaporanPenjualanActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        FrmAbout frmAbout=new FrmAbout();
        
    }//GEN-LAST:event_menuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuInput;
    private javax.swing.JMenuItem menuItemDataBuku;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLaporanBuku;
    private javax.swing.JMenuItem menuItemLaporanPelanggan;
    private javax.swing.JMenuItem menuItemLaporanPenjualan;
    private javax.swing.JMenuItem menuItemPelanggan;
    private javax.swing.JMenuItem menuItemPenjualanBuku;
    private javax.swing.JMenuItem menuItemTentangAplikasi;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
